# Playbook para criar usuarios

- name: Criacao de usuarios nos servidores
  hosts: all
  vars_files:
  - variaveis.yml
  tasks:

  - name: Criando os usuarios nos servidores
    user:
      name: "{{ username }}"
      shell: /bin/bash
