filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
output.logstash:
  hosts: ["log.4labs.example:5443"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
