version: '3'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: chat.4labs.example"

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    volumes:
     - $PWD/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.enable=false"

  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

  traefik:
   image: traefik:latest
   restart: unless-stopped
   command: traefik /
     --docker /
     --api /
     --docker.domain=4labs.example /
     --entrypoints="Name:http Address::80"  /
     --entryPoints="Name:https Address::443" /
     --defaultentrypoints="http,https"
   ports:
     - 80:80
     - 443:443
     - 8080:8080
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
